Repository pagarme/artis, pull requests merged in 2018-04, with the labels that each got.

#154 autocomplete: fix autocomplete address
  src/pages/Addresses.js
Labels: improvement, waiting review

#155 cart-button: fix styles on mobile
  src/themes/default/addressesPage/index.css
  src/themes/default/confirmationPage/index.css
  src/themes/default/footer/index.css
  src/themes/default/paymentPage/index.css
Labels: improvement, waiting review

#157 feat: add invalidation from cloudfront for cdn
  .circleci/config.yml
Labels: waiting review

#158 Add Karoline in team on readme
  README.md
Labels: waiting review

#153 dropdown: fix styles and placeholder
  src/containers/Checkout/index.js
  src/pages/Addresses.js
  src/pages/Payment.js
  src/themes/default/dropdown/index.css
Labels: improvement, waiting review

#159 MultiPayment: Add page
  package.json
  public/index.html
  src/components/Dropdown/Dropdown.js
  src/components/Input/index.js
  src/components/ProgressBar/ProgressBar.test.js
  src/components/ProgressBar/index.js
  src/components/Switch/Switch.test.js
  src/components/Switch/index.js
  src/containers/Checkout/index.js
  src/containers/Checkout/statechart.js
  src/pages/Confirmation.js
  src/pages/Payment.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipaymentOptions.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
  src/pages/Payment/index.js
  src/store.js
  src/themes/default/dropdown/index.css
  src/themes/default/input/index.css
  src/themes/default/paymentPage/index.css
  src/themes/default/switch/index.css
  src/utils/calculations/calcRestAmount.js
  src/utils/calculations/generateInstallments.js
  src/utils/calculations/generateInstallments.test.js
  src/utils/calculations/index.js
  src/utils/helpers/updateMultipleAmount.js
  yarn.lock
Labels: waiting review

#156 radio-group: add new component
  package.json
  src/components/Cart/index.js
  src/components/RadioGroup/RadioGroup.test.js
  src/components/RadioGroup/index.js
  src/containers/Checkout/index.js
  src/pages/Addresses.js
  src/themes/default/addressesPage/index.css
  src/themes/default/customerPage/index.css
  src/themes/default/index.js
  src/themes/default/radio-group/index.css
  yarn.lock
Labels: waiting review

#164 button-text: update button text on last step
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
Labels: improvement, waiting review

#163 chore: fix boleto keys
  src/index.js
  src/utils/strategies/pagarme.js
Labels: waiting review

#165 Credid card: update style
  src/components/Switch/index.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/themes/default/input/index.css
  src/themes/default/paymentPage/index.css
Labels: bug, waiting review

#167 Switch: update styles
  src/components/Switch/index.js
  src/containers/Checkout/index.js
  src/pages/Payment/SwitchPayment.js
  src/pages/Payment/index.js
  src/themes/default/switch/index.css
Labels: bug, waiting review

#168 Success page
  src/components/SuccessInfo/index.js
  src/containers/Checkout/index.js
Labels: waiting review

#169 Svgs were breaking the build
  config/webpack.config.prod.js
Labels: bug, waiting review

#166 multi-payment: update styles
  public/index.html
  src/pages/Payment/MultipaymentOptions.js
  src/pages/Payment/index.js
  src/themes/default/paymentPage/index.css
Labels: improvement, waiting review

#171 boleto: fix boleto payment flow
  src/components/ActionList/index.js
  src/components/SuccessInfo/index.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/SwitchPayment.js
  src/themes/default/errorInfo/index.css
  src/themes/default/paymentPage/index.css
Labels: waiting review

#170 Add more form validations
  src/pages/Addresses.js
  src/pages/Customer.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
  src/utils/helpers/removeMask.js
  src/utils/helpers/removeZipcodeMask.js
  src/utils/validations/card/date.js
  src/utils/validations/cpf.js
  src/utils/validations/index.js
Labels: waiting review

#175 dropdown: fix arrow position
  src/themes/default/dropdown/index.css
Labels: waiting review

#173 boleto: fix texts on boleto flow
  package.json
  src/components/SuccessInfo/index.js
  src/index.js
  src/pages/Payment/BoletoForm.js
  yarn.lock
Labels: waiting review

#177 Fix form behaviour
  src/components/Dropdown/Dropdown.js
  src/components/Footer/index.js
  src/components/Input/index.js
  src/containers/BoletoOptions/index.js
  src/containers/Checkout/index.js
  src/containers/EmailForm/index.js
  src/pages/Addresses.js
  src/pages/Customer.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
  src/themes/default/index.js
  stories/Cart/index.js
Labels: waiting review

#172 payment-page: fix form validation on switch
  src/pages/Payment/SwitchPayment.js
Labels: waiting review

#176 checkout-wrapper: fix creation on open modal
  src/index.js
  src/pages/Payment/CreditCardForm.js
  src/utils/data/colors.js
  src/utils/helpers/createElement.js
Labels: waiting review

#181 former-kit: add lib to the project
  package.json
  src/index.js
  src/pages/Customer.js
  yarn.lock
Labels: waiting review

#180 Multiple Payment: fix installments value
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
Labels: bug, waiting review

#160 Add support a transaction in Mundipagg
  public/assets/css/styles.css
  public/assets/js/custom.js
  public/index.html
  src/containers/Checkout/index.js
  src/index.js
  src/pages/Payment/SwitchPayment.js
  src/utils/parsers/request.js
  src/utils/parsers/requester.test.js
  src/utils/strategies/getStrategyName.js
  src/utils/strategies/index.js
  src/utils/strategies/mundipagg.js
  src/utils/strategies/pagarme.js
  src/utils/strategies/strategy.test.js
  src/utils/strategies/urls.js
  src/utils/validations/index.js
  yarn.lock
Labels: waiting review

#183 chore: add new line max length eslint rule
  .eslintrc
  src/components/ErrorInfo/index.js
  src/components/SuccessInfo/index.js
  src/pages/Addresses.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardForm.js
  src/utils/calculations/generateInstallments.js
  src/utils/data/errorMessages.js
  src/utils/validations/index.js
Labels: improvement, waiting review

#182 Grid former kit
  .storybook/themeDecorator.js
  src/components/ActionList/ActionList.test.js
  src/components/ActionList/index.js
  src/components/ErrorInfo/index.js
  src/components/Footer/index.js
  src/components/Grid/Col.js
  src/components/Grid/Grid.js
  src/components/Grid/Row.js
  src/components/Grid/index.js
  src/components/Header/index.js
  src/components/LoadingInfo/index.js
  src/components/ProgressBar/ProgressBar.test.js
  src/components/ProgressBar/index.js
  src/components/SuccessInfo/index.js
  src/components/index.js
  src/containers/Checkout/index.js
  src/containers/EmailForm/index.js
  src/pages/Addresses.js
  src/pages/Customer.js
  src/pages/Error.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipaymentOptions.js
  src/pages/Payment/MultipleCreditCards.js
  src/themes/default/addressesPage/index.css
  src/themes/default/errorPage/index.css
  src/themes/default/grid/index.css
  src/themes/default/paymentPage/index.css
  stories/Grid/CardSample.js
  stories/Grid/Combinations.js
  stories/Grid/Flexible.js
  stories/Grid/Proportional.js
  stories/Grid/Responsive.js
  stories/Grid/Sizes.js
  stories/Grid/index.js
  stories/Grid/style.css
  stories/index.js
Labels: waiting review

#186 Update checkout and cart size
  src/containers/Checkout/index.js
  src/images/close.svg
  src/themes/default/cart/index.css
  src/themes/default/checkout/index.css
Labels: waiting review

#174 Fix/amount
  public/index.html
  src/actions/index.js
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/containers/Checkout/index.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
  src/reducers/reducers.test.js
  src/reducers/transactionValues.js
  src/utils/calculations/generateInstallments.js
  src/utils/calculations/generateInstallments.test.js
  src/utils/helpers/formatInstallments.js
  src/utils/helpers/formatToBRL.js
  src/utils/helpers/formatToCents.js
  src/utils/helpers/getInputAmountValue.js
  src/utils/helpers/getInstallments.js
Labels: waiting review

#188 Update header
  src/components/Header/Header.test.js
  src/components/Header/index.js
  src/components/ProgressBar/ProgressBar.test.js
  src/components/ProgressBar/index.js
  src/containers/Checkout/index.js
  src/containers/Checkout/steps.js
  src/images/confirmation.svg
  src/images/map.svg
  src/images/payment.svg
  src/images/user.svg
  src/themes/default/colors.css
  src/themes/default/header/index.css
  src/themes/default/index.js
  src/themes/default/linear-progress/index.css
  src/themes/default/progressBar/index.css
  src/utils/data/colors.js
Labels: waiting review

#187 footer: update footer component
  src/components/Footer/Footer.test.js
  src/components/Footer/index.js
  src/containers/Checkout/index.js
  src/images/escudo.svg
  src/themes/default/checkout/index.css
  src/themes/default/footer/index.css
  stories/Footer/index.js
Labels: waiting review

#191 switch: update component style
  src/containers/Checkout/index.js
  src/pages/Addresses.js
  src/themes/default/index.js
  src/themes/default/radio-group/index.css
  src/themes/default/switch/index.css
  stories/Switch/index.js
  stories/Switch/style.css
Labels: waiting review

#193 header: update logo style
  src/components/Header/index.js
  src/themes/default/header/index.css
Labels: bug, waiting review

#189 button: change css to former-kit
  src/components/ActionList/index.js
  src/components/Button/Button.test.js
  src/components/Button/index.js
  src/components/Cart/index.js
  src/components/index.js
  src/containers/EmailForm/index.js
  src/images/navigate_back.svg
  src/images/navigate_next.svg
  src/pages/Addresses.js
  src/pages/Customer.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/MultipaymentOptions.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/SwitchPayment.js
  src/themes/default/button/index.css
  stories/Button/index.js
Labels: improvement, waiting review

#192 chore: add tests to the project
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/components/SuccessInfo/index.js
  src/pages/Addresses.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/utils/calculations/generateInstallments.js
  src/utils/calculations/generateInstallments.test.js
  src/utils/helpers/formatInstallments.js
  src/utils/helpers/formatToBRL.js
  src/utils/helpers/formatToCents.js
  src/utils/helpers/getInputAmountValue.js
  src/utils/helpers/getInstallments.js
  src/utils/helpers/helpers.test.js
  src/utils/helpers/removeMask.js
  src/utils/masks/index.js
  src/utils/masks/masks.test.js
  src/utils/strategies/pagarme.js
  src/utils/validations/index.js
Labels: help wanted, waiting review

#190 Add/dropdown redesign
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.test.js
  src/components/Dropdown/index.js
  src/components/index.js
  src/pages/Addresses.js
  src/pages/Payment/CreditCardForm.js
  src/themes/default/dropdown/index.css
  stories/FormFields/examples/Dropdown.js
  stories/FormFields/style.css
Labels: improvement, waiting review

#194 loading_info: add to storybook and update styles
  .storybook/themeDecorator.js
  src/components/LoadingInfo/index.js
  src/themes/default/button/index.css
  src/themes/default/loadingInfo/index.css
  stories/Loading/index.js
  stories/Loading/style.css
  stories/index.js
Labels: improvement, waiting review

#185 input: add forminput from former-kit
  src/components/Input/Input.test.js
  src/components/Input/index.js
  src/components/index.js
  src/containers/Checkout/index.js
  src/containers/EmailForm/EmailForm.test.js
  src/containers/EmailForm/index.js
  src/pages/Addresses.js
  src/pages/Customer.js
  src/pages/Payment/BoletoForm.js
  src/pages/Payment/CreditCardForm.js
  src/themes/default/addressesPage/index.css
  src/themes/default/checkout/index.css
  src/themes/default/customerPage/index.css
  src/themes/default/index.js
  src/themes/default/input/index.css
  src/utils/helpers/getAddress.js
  stories/FormFields/examples/Input.js
Labels: waiting review

#197 customer-page: update layout
  src/pages/Customer.js
  src/themes/default/colors.css
  src/themes/default/customerPage/index.css
  src/themes/default/input/index.css
Labels: waiting review

#195 Update cart layout
  package.json
  public/assets/js/apiParameters.js
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/containers/Checkout/index.js
  src/images/cart.svg
  src/images/clear-close.svg
  src/pages/Addresses.js
  src/reducers/pageInfo.js
  src/themes/default/cart/index.css
  src/themes/default/checkout/index.css
  src/themes/default/header/index.css
  stories/Cart/index.js
  stories/Cart/style.css
  stories/index.js
  yarn.lock
Labels: waiting review

#200 API: add softDescriptor to boleto
  public/assets/js/apiParameters.js
  src/utils/strategies/pagarme.js
Labels: improvement, waiting review

#201 credit_card: add function to change object installment
  src/pages/Payment/SwitchPayment.js
  src/utils/helpers/changeInstallmentsToArray.js
  src/utils/helpers/helpers.test.js
Labels: improvement, waiting review

#203 api: move shippingRate from cart to shipping object
  public/assets/js/apiParameters.js
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/containers/Checkout/index.js
  src/utils/strategies/mundipagg.js
Labels: improvement, waiting review

#204 button: update disable style
  src/themes/default/button/index.css
  stories/Button/index.js
Labels: improvement, waiting review

#205 switch: change color and other styles
  src/themes/default/switch/index.css
  stories/Switch/index.js
Labels: improvement, waiting review
