Repository pagarme/artis, pull requests merged in 2018-05, with the labels that each got.

#207 cart: fix amount
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/containers/Checkout/CheckoutContainer.test.js
  src/containers/Checkout/index.js
  src/store.js
Labels: bug, waiting review

#211 Creditcard payment screen
  package.json
  src/components/Switch/Switch.test.js
  src/components/Switch/index.js
  src/components/index.js
  src/containers/Checkout/index.js
  src/pages/Payment/CreditCard.js
  src/pages/Payment/SwitchPayment.js
  src/pages/Payment/index.js
  src/themes/default/creditcardPage/index.css
  src/themes/default/index.js
  src/themes/default/paymentPage/index.css
  stories/FormFields/examples/Switch.js
  stories/FormFields/index.js
  stories/index.js
  yarn.lock
Labels: improvement, waiting review

#209 Update payment selection page layout
  public/assets/js/apiParameters.js
  src/components/Cart/index.js
  src/containers/Checkout/index.js
  src/images/boleto.svg
  src/images/close.svg
  src/images/credit-card-more-boleto.svg
  src/images/credit-card.svg
  src/images/two-credit-cards.svg
  src/pages/Payment/MultipaymentOptions.js
  src/pages/Payment/index.js
  src/themes/default/index.js
  src/themes/default/paymentoptionsPage/index.css
Labels: improvement, waiting review

#214 chore: add codeowners file
  .github/CODEOWNERS
Labels: waiting review

#212 creditcard: fix transaction flow
  src/pages/Payment/CreditCard.js
Labels: bug, waiting review

#213 layout: update general layout
  src/components/ActionList/index.js
  src/containers/Checkout/index.js
  src/containers/EmailForm/index.js
  src/pages/Customer.js
  src/pages/Payment/CreditCardAndBoleto.js
  src/pages/Payment/CreditCardForm.js
  src/pages/Payment/MultipleCreditCards.js
  src/pages/Payment/PaymentOptions.js
  src/pages/Payment/index.js
  src/themes/default/billingPage/index.css
  src/themes/default/button/index.css
  src/themes/default/index.js
  src/themes/default/paymentPage/index.css
  src/themes/default/paymentoptionsPage/index.css
  src/themes/default/shippingPage/index.css
  stories/Button/index.js
Labels: waiting review

#218 analysis: add analysis page
  src/components/MessageInfo/Analysis/index.js
  src/components/index.js
  src/containers/Checkout/index.js
  src/containers/Checkout/statechart.js
  src/images/confirmacao_analise.svg
  src/themes/default/index.js
  src/themes/default/messageInfo/analysis/index.css
  stories/FinalPages/index.js
Labels: waiting review

#215 Add/success message info
  public/assets/js/apiParameters.js
  src/components/DarkButton/index.js
  src/components/MessageInfo/Success/index.js
  src/components/SuccessInfo/index.js
  src/components/index.js
  src/containers/Checkout/index.js
  src/images/closeX.svg
  src/images/confirmacao_sucesso.svg
  src/images/copy.svg
  src/images/download.svg
  src/images/email.svg
  src/images/pedido.svg
  src/pages/Payment/PaymentOptions.js
  src/themes/default/darkButton/index.css
  src/themes/default/index.js
  src/themes/default/messageInfo/success/index.css
  src/themes/default/paymentoptionsPage/index.css
  src/themes/default/successInfo/index.css
  stories/DarkButton/index.js
  stories/DarkButton/style.css
  stories/FinalPages/index.js
  stories/index.js
Labels: improvement, waiting review

#216 customer_page: update mobile media
  src/themes/default/customerPage/index.css
Labels: improvement, waiting review

#219 error-page: update style
  src/components/MessageInfo/Analysis/index.js
  src/components/MessageInfo/Error/index.js
  src/themes/default/messageInfo/analysis/index.css
  src/themes/default/messageInfo/error/index.css
Labels: waiting review

#225 Add/boleto page
  src/components/MessageInfo/Success/index.js
  src/containers/Checkout/index.js
  src/images/boleto-dark.svg
  src/pages/Payment/Boleto.js
  src/pages/Payment/BoletoForm.js
  src/themes/default/boletoPage/index.css
  src/themes/default/index.js
  stories/Pages/index.js
  stories/Pages/style.css
  stories/index.js
Labels: improvement, waiting review

#227 boleto: update mobile layout
  src/pages/Payment/Boleto.js
  src/themes/default/boletoPage/index.css
Labels: improvement, waiting review

#222 success-page: update style
  src/components/MessageInfo/Success/index.js
  src/pages/Payment/CreditCard.js
  src/themes/default/checkout/index.css
  src/themes/default/messageInfo/success/index.css
  stories/Pages/index.js
Labels: waiting review

#223 Add simple integration
  public/assets/css/styles.css
  public/assets/js/customParameters.js
  public/assets/js/panel.js
  public/assets/js/simpleParameters.js
  public/index.html
  public/simple.html
  src/index.js
  src/themes/default/checkout/index.css
Labels: waiting review

#229 header: add navigation on mobile
  src/components/Header/index.js
  src/containers/Checkout/index.js
  src/images/navigate_back.svg
  src/themes/default/header/index.css
Labels: waiting review

#228 cart: update mobile layout
  src/components/Cart/Cart.test.js
  src/components/Cart/index.js
  src/themes/default/cart/index.css
Labels: improvement, waiting review

#230 Fix transaction with boleto
  src/pages/Payment/Boleto.js
Labels: waiting review

#233 project: add Docker
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  docker/docker_bash.sh
  docker/docker_bootstrap.sh
  docker/docker_run.sh
Labels: improvement, waiting review

#237 billing: add state validation
  src/pages/Billing.js
Labels: improvement, waiting review

#236 billing: add complement validation
  src/pages/Billing.js
Labels: improvement, waiting review

#239 shipping: add complement and state validation
  src/pages/Shipping.js
Labels: improvement, waiting review

#238 installments: update get installments method
  public/assets/js/customParameters.js
  src/App.js
  src/actions/index.js
  src/components/LoadingInfo/index.js
  src/containers/Checkout/index.js
  src/index.js
  src/pages/Payment/CreditCard.js
  src/reducers/pageInfo.js
  src/reducers/reducers.test.js
  src/reducers/transactionValues.js
  src/themes/default/checkout/index.css
  src/themes/default/loadingInfo/index.css
  src/utils/helpers/getInstallments.js
  src/utils/helpers/helpers.test.js
  src/utils/strategies/mundipagg.js
  src/utils/strategies/pagarme.js
  src/utils/strategies/urls.js
Labels: waiting review

#234 project: update tests and add cypress
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/simple/billing.spec.js
  cypress/integration/simple/boleto.spec.js
  cypress/integration/simple/creditCard.spec.js
  cypress/integration/simple/customer.spec.js
  cypress/integration/simple/shipping.spec.js
  package.json
  src/components/DarkButton/DarkButton.test.js
  src/containers/EmailForm/index.js
  src/themes/default/index.js
Labels: improvement, waiting review
