Repository pagarme/artis, pull requests merged in 2018-07, with the labels that each got.

#245 navigation: fix flow when pages are not visible
  src/containers/Checkout/index.js
  src/containers/Checkout/statechart.js
  src/pages/Billing.js
  src/pages/Payment/PaymentOptions.js
  src/pages/Shipping.js
  src/reducers/pageInfo.js
Labels: waiting review

#248 button: update children
  src/components/Button/index.js
Labels: bug, waiting review

#249 chore: remove repeated semantic html tags
  src/components/MessageInfo/Error/index.js
  src/components/MessageInfo/Success/index.js
  src/pages/Billing.js
  src/pages/Customer.js
  src/pages/Payment/Boleto.js
  src/pages/Payment/CreditCard.js
  src/pages/Payment/PaymentOptions.js
  src/pages/Shipping.js
Labels: waiting review

#254 Fix/input background chrome
  src/themes/default/input/index.css
Labels: improvement, waiting review

#255 shipping: returning object on callback
  src/utils/strategies/pagarme.js
Labels: bug, waiting review

#253 pages: add focus on first input
  src/pages/Billing.js
  src/pages/Customer.js
  src/pages/Payment/CreditCard.js
  src/pages/Shipping.js
Labels: improvement, waiting review

#250 api: update checkout open method
  public/assets/js/panel.js
  public/assets/js/simpleParameters.js
  src/index.js
Labels: improvement, waiting review

#256 amount: update handle amount in checkout
  src/containers/Checkout/index.js
  src/store.js
  src/utils/calculations/calcAmount.js
  src/utils/calculations/index.js
  src/utils/validations/apiValidation.js
Labels: improvement, waiting review

#252 Adiciona suporte ao CNPJ no customer
  public/assets/js/customParameters.js
  src/pages/Customer.js
  src/utils/validations/cnpj.js
  src/utils/validations/cnpj.test.js
  src/utils/validations/index.js
Labels: waiting review

#261 shipping: fix pagarme strategy payload
  src/utils/strategies/pagarme.js
Labels: improvement

#258 transaction: add user_agent header
  src/utils/helpers/getCheckoutVersion.js
  src/utils/strategies/pagarme.js
Labels: blocker

#263 one-click-buy: update config
  public/assets/js/customParameters.js
  src/containers/Checkout/index.js
  src/pages/Payment/CreditCard.js
Labels: improvement, waiting review

#262 one-click-buy: update cardId config position
  public/assets/js/customParameters.js
  src/store.js
Labels: waiting review

#251 Checkout: update simple integration
  public/assets/js/panel.js
  public/assets/js/simpleParameters.js
  src/App.js
  src/containers/Checkout/index.js
  src/index.js
  src/reducers/reducers.test.js
  src/reducers/transactionValues.js
  src/utils/helpers/getParentElement.js
Labels: improvement, waiting review

#260 Add pages callbacks
  public/assets/js/customParameters.js
  public/assets/js/panel.js
  src/containers/Checkout/index.js
  src/index.js
  src/pages/Billing.js
  src/pages/Customer.js
  src/pages/Payment/Boleto.js
  src/pages/Payment/CreditCard.js
  src/pages/Payment/PaymentOptions.js
  src/pages/Shipping.js
Labels: waiting review

#265 error-message: fix back button
  src/components/MessageInfo/Error/index.js
  src/containers/Checkout/index.js
Labels: bug, waiting review

#267 cypress: fix tests
  .circleci/config.yml
  .gitignore
  cypress/integration/simple/billing.spec.js
  cypress/integration/simple/boleto.spec.js
  cypress/integration/simple/creditCard.spec.js
  cypress/integration/simple/customer.spec.js
  cypress/integration/simple/shipping.spec.js
  package.json
  public/assets/js/simpleParameters.js
  src/pages/Billing.js
  src/pages/Customer.js
  src/pages/Payment/CreditCard.js
  src/pages/Shipping.js
  yarn.lock
Labels: bug, improvement, waiting review
